### PR TITLE
Replace ctr i pull/push with nerdctl -q

### LINKED ISSUE #403: Change `ctr i pull` to `nerdctl pull -q` in integration tests
Changing `ctr i pull` to `nerdctl pull -q` can reduce 1/3 of useless output from integration tests, which still log errors from pull if there is any.

`ctr i pull` produces a lot of logs (downloading/waiting/done/etc + periodic refresh), making integration test output extremely hard to read.

In my test run, `make integration > test.log` produces 33370 line of output, of which ~11690 lines are from `ctr i pull`, e.g.,

```shell
...
public.ecr.aws/docker/library/rabbitmq:3.11.7:                                    resolved       |[32m++++++++++++++++++++++++++++++++++++++[0m| 
index-sha256:8501c659bd79d2be95b108749bde471209f754d32b24772f08a7a2b99bd2f754:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
manifest-sha256:b542092a88c107f199c71c6c34b41ff0185902e6172fe8446726cd996a24e50a: done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:7608715873ec5c02d370e963aa9b19a149023ce218887221d93fe671b3abbf58:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
config-sha256:19cb9635d301defa5cafbbc09a3e41c41c4aa6730a906c14a4de67d5dc672f15:   done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:a8776120650a7488d4e1fd5068d423776b6e8fa49559aad7e5e6e9f75c7f858e:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:c3710248cc06487708c6d60c5aef649f035b670c5b518f5aed9b31957647dff8:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:6610e44d931fe606a8e2efe2375a845cdc6531ed30deff5aff8daac655bca5dc:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:e81638db5918e47519d6d1112954a0b3f2474396c36048ef1960ed6170a4ff6d:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:17d592636c2e45f00cf8722b195400be5fec618504f5ac4482867d82150df4e7:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:6e81be32de605ae487c6e04edc9fe355bd6cafb3c18f670ea79e2893b564b6b5:    downloading    |[32m++++++++++++++++++++++++++++++++[0m------| 42.0 MiB/48.7 MiB 
layer-sha256:1280b213aef7cc80e73940a617b0e5fac4acbe4142832c510783b0eaf6dd6621:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:8682ddf02c09027a6510837a7087ef4a9da15de952bca1629422062ef3fbc0c6:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:163d89fff8cfd51b97557be461eab292eb9cb8c200e386971435851898c7c560:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
elapsed: 0.7 s                                                                    total:  90.2 M (128.6 MiB/s)                                     
public.ecr.aws/docker/library/rabbitmq:3.11.7:                                    resolved       |[32m++++++++++++++++++++++++++++++++++++++[0m| 
index-sha256:8501c659bd79d2be95b108749bde471209f754d32b24772f08a7a2b99bd2f754:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
manifest-sha256:b542092a88c107f199c71c6c34b41ff0185902e6172fe8446726cd996a24e50a: done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:7608715873ec5c02d370e963aa9b19a149023ce218887221d93fe671b3abbf58:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
config-sha256:19cb9635d301defa5cafbbc09a3e41c41c4aa6730a906c14a4de67d5dc672f15:   done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:a8776120650a7488d4e1fd5068d423776b6e8fa49559aad7e5e6e9f75c7f858e:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:c3710248cc06487708c6d60c5aef649f035b670c5b518f5aed9b31957647dff8:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:6610e44d931fe606a8e2efe2375a845cdc6531ed30deff5aff8daac655bca5dc:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:e81638db5918e47519d6d1112954a0b3f2474396c36048ef1960ed6170a4ff6d:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:17d592636c2e45f00cf8722b195400be5fec618504f5ac4482867d82150df4e7:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:6e81be32de605ae487c6e04edc9fe355bd6cafb3c18f670ea79e2893b564b6b5:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:1280b213aef7cc80e73940a617b0e5fac4acbe4142832c510783b0eaf6dd6621:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:8682ddf02c09027a6510837a7087ef4a9da15de952bca1629422062ef3fbc0c6:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
layer-sha256:163d89fff8cfd51b97557be461eab292eb9cb8c200e386971435851898c7c560:    done           |[32m++++++++++++++++++++++++++++++++++++++[0m| 
....
```

As a comparsion in `nerdctl pull -q`:

```shell
# no output if pull succeeds.
$ nerdctl snd pull golang -q
# output error if there is.
$ nerdctl pull fdsafdsf -q
INFO[0000] trying next host                              error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io
FATA[0000] failed to resolve reference "docker.io/library/fdsafdsf:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

### PR DESCRIPTION
**Pull request by sparr**
*Issue #, if available:*
Closes #403 

*Description of changes:*
Replace `ctr i pull`/`push` with `nerdctl -q` to quieten log output during image operations.

*Testing performed:*
Ran integration test suite successfully.
Also ran one test, LazyPullWithSparseIndex, with and without this change, to compare output verbosity:
```
% wc out.before
  1372   8285 248098 out.before

% wc out.after
  1166   7415 215406 out.after
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: integration/testutil.go [hunk 1]
```diff
@@ -304,7 +304,8 @@ func dockerhub(name string, opts ...imageOpt) imageInfo {
 	return i
 }
 
-func encodeImageInfo(ii ...imageInfo) [][]string {
+// encodeImageInfoCtr assembles command line options for pulling or pushing an image using ctr
+func encodeImageInfoCtr(ii ...imageInfo) [][]string {
```
Comment (sparr) [inline integration/testutil.go:308]: This function is no longer used but I predict it will be a useful helper when we need to explicitly call `ctr` in the future for features not present in `nerdctl`.

**Comment by Kern--** [comment]
How does pushing to the registry work without credentials?

**Comment by sparr** [comment]
@Kern-- credentials are cached when `newShellWithRegistry` does `nerdctl login ...`

**Review by sbuckfelder — APPROVED** [review]
LGTM

**Review by Kern-- — APPROVED** [review]
