### PR TITLE
`soci push` always pushes the most recent index

### LINKED ISSUE #242: SOCI CLI doesn't always push the most recently created index
**Describe the bug**
Currently, the `soci push` command promises to push the most recently created soci index to the remote repository. However, it doesn't always do that.

**Steps To Reproduce**
```
$  sudo ./soci index ls 
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM

$ sudo ./soci create docker.io/library/rabbitmq:latest

$ sudo ./soci index ls
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM
sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a    1436    docker.io/library/rabbitmq:latest    linux/amd64

$ sudo ./soci index push docker.io/library/rabbitmq:latest
pushing index with digest: sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a
...

$ sudo ./soci create docker.io/library/rabbitmq:latest --span-size 128000
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM
sha256:77ba6f5324398e1b3f1344339b74ec6fb66c8eff51d8e8caa66677070ea684da    1438    docker.io/library/rabbitmq:latest    linux/amd64
sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a    1436    docker.io/library/rabbitmq:latest    linux/amd64

$ sudo ./soci index push docker.io/library/rabbitmq:latest
pushing index with digest: sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a
...
```

In both instances, the SOCI CLI tried pushing the same index. 

**Expected behavior**
`sudo ./soci push <image ref>` pushes the most recently created index using the timestamp of index creation. 

**Configuration (please complete the following information):**
 - OS: Ubuntu 22.04
 - Snapshotter Version:  71ff12755ab7f18a3c507
 - Containerd Version:   1.6.13

**Additional context**

RabbitMQ image: docker.io/library/rabbitmq:latest (sha256:90e20c3d3dfc1a50a92ada5fceb45155c448dc95c28e8fa907912beb8e79ce0a)

### PR DESCRIPTION
**Pull request by rdpsin**
This commit fixes a bug in `soci push` where it was not always guaranteed to push the most recently created index. Added a `CreatedAt` value to each entry in the artifacts db.

Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>

*Issue #, if available:*
Fixes #242 

*Description of changes:*

*Testing performed:*

```
% sudo ./soci index ls 
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM

% sudo ./soci create docker.io/library/rabbitmq:latest

% sudo ./soci index ls
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM       CREATED      
sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a    1436    docker.io/library/rabbitmq:latest    linux/amd64    5s ago   

% sudo ./soci push docker.io/library/rabbitmq:latest 
pushing soci index with digest: sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a


% sudo ./soci index ls                                                   
DIGEST                                                                     SIZE    IMAGE REF                            PLATFORM       CREATED      
sha256:77ba6f5324398e1b3f1344339b74ec6fb66c8eff51d8e8caa66677070ea684da    1438    docker.io/library/rabbitmq:latest    linux/amd64    6s ago       
sha256:f117044f3ed73c5fb9780ca4a2ba50dc2f1bfa1aaf320738bb007cb73982df6a    1436    docker.io/library/rabbitmq:latest    linux/amd64    1m26s ago   

% sudo ./soci push docker.io/library/rabbitmq:latest                     
pushing soci index with digest: sha256:77ba6f5324398e1b3f1344339b74ec6fb66c8eff51d8e8caa66677070ea684da
...
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: soci/artifacts.go [hunk 1]
```diff
@@ -293,13 +297,22 @@ func loadArtifact(artifactBkt *bolt.Bucket, digest string) (*ArtifactEntry, erro
 	if err != nil {
 		return nil, err
 	}
+	createdAt := time.Now()
```
Comment (Kern--) [inline soci/artifacts.go:300]: Do we want to default to `time.Now()`? That would mean indices created before this change would always show up as the newest ones, right?

File: cmd/soci/commands/push.go [hunk 2]
```diff
@@ -102,7 +102,6 @@ if they are available in the snapshotter's local content store.
 			if err != nil {
 				return fmt.Errorf("cannot create OCI local store: %w", err)
 			}
-
 			indexDesc := indexDescriptors[len(indexDescriptors)-1]
```
Comment (Kern--) [inline cmd/soci/commands/push.go:105]: I feel like I must be missing something here, but your code looks like it sorts oldest to newest (which should work here), but the example in the description looks like it's printing newest to oldest. How do they both work?

**Review by djdongjin — COMMENTED** [review]
Do we want to have an integration test for this case? since we already have some integration test for `push`

File: cmd/soci/commands/push.go (hunk 2 above)
Comment (rdpsin) [reply cmd/soci/commands/push.go:105]: The `list` command does not use `GetIndexDescriptorCollection` like `push` does; instead, it directly talks to the artifacts db. The sorting is done in `GetIndexDescriptorCollection`.

File: soci/artifacts.go (hunk 1 above)
Comment (rdpsin) [reply soci/artifacts.go:300]: Yes, I'm not sure what a good default is in this case? Could use `*time.Time` instead. Honestly, I don't think maintaining backwards compatibility here is really important.

**Review by hanyuel — DISMISSED** [review]

**Comment by hanyuel** [comment]
> Do we want to have an integration test for this case? since we already have some integration test for `push`

+1. would be nice to write some test that validates the change

**Comment by rdpsin** [comment]
Added integration test.

File: soci/artifacts.go (hunk 1 above)
Comment (Kern--) [reply soci/artifacts.go:300]: Fair point about backwards compatibility. I think `time.Time{}` might be more defensive. If we do have some sort of regression, 0001-01-01 is pretty easy to spot and I can imagine some subtly frustrating bugs if your index crated time keeps changing to be this very instant.

Comment (rdpsin) [reply soci/artifacts.go]: Done.

**Review by djdongjin — DISMISSED** [review]

**Review by kzys — DISMISSED** [review]

File: integration/push_test.go [hunk 3]
```diff
@@ -108,8 +109,111 @@ level = "debug"
...
+
+				if index != pushedIndex {
+					t.Fatalf("incorrect index pushed to remote registry; expected %s, got %s", index, pushedIndex)
+				}
+			}
+		})
+	}
 }
+
+// TODO: There is a bit of duplication going on here.
```
Comment (Kern--) [inline integration/push_test.go:205]: Can we create an issue referencing this?

**Review by Kern-- — APPROVED** [review]

**Review by hanyuel — APPROVED** [review]
