### PR TITLE
Fix index info command with containerd content store

### LINKED ISSUE #983: [Bug] Unable to inspect a SOCI Index stored in the containerd content store with the SOCI CLI
### Description

You can create, list and push a SOCI index when the `--content-store containerd` flag but you are unable to inspect it.

```bash
$ sudo soci --content-store containerd create $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-demo:latest
ztoc skipped - layer sha256:86f45faecc5b2221d3e18541dc4f77749f7bd91ad55711355ab073c8f8c28157 (application/vnd.docker.image.rootfs.diff.tar.gzip) size 625 is less than min-layer-size 10485760
layer sha256:0b4a6f011995244a95bff79a1298e83d230bc0aa22871a9c510745cafebec227 -> ztoc sha256:102c0caa2b8638cc0437e4b4ccec60bc8830ad2b21c12f40131ab9e0d06d5b7e
layer sha256:59f463217446c74400d2e5a6bebcde9bf0870fe0eb3457dd592e90c4eb600293 -> ztoc sha256:583c0ddb446ed5367b352adad9168edee91e9fd80bfd6009bdfb70975f278198

$ sudo soci --content-store containerd push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-demo:latest
checking if a soci index already exists in remote repository...
pushing soci index with digest: sha256:7ef67b1d588c653da8a3fd65a8c1217e7faefbf7ba886d911012ca04c1742794
...

$ sudo soci --content-store containerd index ls
DIGEST                                                                     SIZE    IMAGE REF                                                         PLATFORM       MEDIA TYPE                                    CREATED      
sha256:7ef67b1d588c653da8a3fd65a8c1217e7faefbf7ba886d911012ca04c1742794    1211    $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx-demo:latest    linux/amd64    application/vnd.oci.image.manifest.v1+json    2m54s ago

$ sudo soci --content-store containerd index info sha256:7ef67b1d588c653da8a3fd65a8c1217e7faefbf7ba886d911012ca04c1742794
soci: context deadline exceeded
```

I did double check and they are stored in the containerd content store correctly.

```bash
$ sudo ctr content ls -q | grep 7ef
sha256:7ef67b1d588c653da8a3fd65a8c1217e7faefbf7ba886d911012ca04c1742794

$ sudo cat /var/lib/containerd/io.containerd.content.v1.content/blobs/sha256/7ef67b1d588c653da8a3fd65a8c1217e7faefbf7ba886d911012ca04c1742794 | jq -r '.'
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.amazon.soci.index.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
...
```

### Steps to reproduce the bug

_No response_

### Describe the results you expected

To be able to inspect the local SOCI Index.

### Host information

```bash
$ sudo soci --version
soci version v0.4.0 894c8ece8a2177928343899b1f897d2164c98254

$ sudo ctr --version
ctr github.com/containerd/containerd 1.7.2
```

### Any additional context or information about the bug

_No response_

### PR DESCRIPTION
**Pull request by austinvazquez**
**Issue #, if available:**
Fixes #983 

**Description of changes:**
Previously SOCI CLI index info command would fail with context deadline exceeded error when the content store was set to containerd. The root cause was the default global duration for the app context is zero if not set. The result was Go context with an immediate deadline thus resulting in the error. The fix is to not set a deadline if no duration is provided.

**Testing performed:**
Before changes:
```
$ mysudo soci --content-store containerd index info sha256:8aad6c25d856dabc72284325e14dc5ea2df228c3fd6b5a96ab46854def73ea50
soci: context deadline exceeded
$ 
```

After changes:
```
$ mysudo soci --content-store containerd index info sha256:8aad6c25d856dabc72284325e14dc5ea2df228c3fd6b5a96ab46854def73ea50
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.amazon.soci.index.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/octet-stream",
      "digest": "sha256:d548f77fc4f9ad31bf390ccaab4c5ffa97f7319f921a3125e5d7daa865c0a8a1",
      "size": 1229704,
      "annotations": {
        "com.amazon.soci.image-layer-digest": "sha256:5e8117c0bd28aecad06f7e76d4d3b64734d59c1a0a44541d18060cd8fba30c50",
        "com.amazon.soci.image-layer-mediaType": "application/vnd.oci.image.layer.v1.tar+gzip"
      }
    }
  ],
  "subject": {
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "digest": "sha256:149d67e29f765f4db62aa52161009e99e389544e25a8f43c8c89d4a445a7ca37",
    "size": 424
  },
  "annotations": {
    "com.amazon.soci.build-tool-identifier": "AWS SOCI CLI v0.1"
  }
}$ 
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: cmd/soci/commands/index/info.go [hunk 1]
```diff
@@ -32,12 +34,24 @@ import (
 	"github.com/urfave/cli"
 )
 
+var (
+	defaultIndexInfoTimeout = 10 * time.Second
```
Comment (Kern--) [inline cmd/soci/commands/index/info.go:38]: It feels weird to set a default timeout for just `index info`. `internal.AppContext` already sets the timeout on the context if it's > 0. If we want a default, that should be on the flag itself, but I don't  think we do.

Comment (austinvazquez) [reply cmd/soci/commands/index/info.go:38]: Okay yea, should be fine to have no timeout, and let users set it if they are experiencing issues.

**Review by sondavidb — APPROVED** [review]

**Review by Kern-- — APPROVED** [review]
