### PR TITLE
Disable unused containerd plugins in integ tests

### LINKED ISSUE #377: [BUG] Unused plugins produce error messages in logs on expected failure to load
**Describe the bug**
Containerd feature plugins such as OpenTelemetry and CNI, as well as filesystem plugins like aufs and btrfs, will not load if modules are unavailable or configuration files are not present. This produces error messages, despite almost always not being an error condition. Some of these are at different log severity levels (info, warning, error).

**Steps To Reproduce**
`make integration`

**Expected behavior**
Avoid these errors, or at least logging them, when they are expected behavior.

**Additional context**
`make integration` produces 19 instances of each of the following:
* `{"error":"aufs is not supported (modprobe aufs failed: exec: \"modprobe\": executable file not found in $PATH \"\"): skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..."`
* `{"error":"cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config","level":"error","msg":"failed to load cni during init, please check CRI plugin status before setting up network for pods"`
* `{"error":"devmapper not configured","level":"warning","msg":"could not use snapshotter devmapper in metadata plugin"`
* `{"error":"devmapper not configured","level":"warning","msg":"failed to load plugin io.containerd.snapshotter.v1.devmapper"`
* `{"error":"no OpenTelemetry endpoint: skip plugin","level":"error","msg":"failed to initialize a tracing processor \"otlp\""`
* `{"error":"no OpenTelemetry endpoint: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..."`
* `{"error":"path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (tmpfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..."`
* `{"error":"path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin","level":"info","msg":"skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..."`

and 43 instances of:
* `level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"`
* `level=error msg="failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exec: \"modprobe\": executable file not found in $PATH \"\"): skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (tmpfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1`
* `level=info msg="skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1`
* `level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"`
* `level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"`

### PR DESCRIPTION
**Pull request by Kern--**
*Issue #, if available:*
Closes #377 

*Description of changes:*
This change disables several containerd plugins that we're not using so they don't clutter the integ test logs with setup failures.

There are a lot more containerd logs, but here are the relevant ones to this change:

Before:
```
time="2023-02-15T17:16:28Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
time="2023-02-15T17:16:28.173825328Z" level=info msg="starting containerd" revision=299b677800044531671d336af5f0976fd2e6ac70 version=v1.6.17
time="2023-02-15T17:16:28.189613676Z" level=info msg="loading plugin \"io.containerd.content.v1.content\"..." type=io.containerd.content.v1
time="2023-02-15T17:16:28.189682682Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.aufs\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.189781232Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.aufs\"..." error="aufs is not supported (modprobe aufs failed: exec: \"modprobe\": executable file not found in $PATH \"\"): skip plugin" type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.189833756Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.189973342Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.btrfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.btrfs (tmpfs) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.189988318Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.devmapper\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.189999106Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
time="2023-02-15T17:16:28.190010276Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.native\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.190034499Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.overlayfs\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.190136853Z" level=info msg="loading plugin \"io.containerd.snapshotter.v1.zfs\"..." type=io.containerd.snapshotter.v1
time="2023-02-15T17:16:28.190260705Z" level=info msg="skip loading plugin \"io.containerd.snapshotter.v1.zfs\"..." error="path /var/lib/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
```

After:
```
{"level":"info","msg":"starting containerd","revision":"299b677800044531671d336af5f0976fd2e6ac70","time":"2023-02-15T00:39:39.174449547Z","version":"v1.6.17"}
{"level":"info","msg":"loading plugin \"io.containerd.content.v1.content\"...","time":"2023-02-15T00:39:39.186902483Z","type":"io.containerd.content.v1"}
{"level":"info","msg":"loading plugin \"io.containerd.snapshotter.v1.native\"...","time":"2023-02-15T00:39:39.186991924Z","type":"io.containerd.snapshotter.v1"}
{"level":"info","msg":"loading plugin \"io.containerd.snapshotter.v1.overlayfs\"...","time":"2023-02-15T00:39:39.187024919Z","type":"io.containerd.snapshotter.v1"}
```

*Testing performed:*
`make check && make integration`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: integration/testutil.go [hunk 1]
```diff
@@ -521,7 +531,7 @@ func newSnapshotterBaseShell(t *testing.T) (*shell.Shell, func() error) {
 	}
 	sh := shell.New(de, testutil.NewTestingReporter(t))
 	if !isTestingBuiltinSnapshotter() {
-		if err := testutil.WriteFileContents(sh, defaultContainerdConfigPath, []byte(proxySnapshotterConfig), 0600); err != nil {
```
Comment (sparr) [inline integration/testutil.go:524]: Is the containerd `proxy_plugins.proxy_plugins.soci` configuration no longer necessary?

**Review by sparr — APPROVED** [review]
Thanks!

**Comment by sbuckfelder** [comment]
Any results?  Like examples of how the logs changed?

**Review by sbuckfelder — APPROVED** [review]
LGTM

**Review by hanyuel — APPROVED** [review]

File: integration/config/etc/containerd/config.toml [hunk 2]
```diff
@@ -1,6 +1,16 @@
...
 version = 2
 
+disabled_plugins = [
+	"io.containerd.snapshotter.v1.aufs",
+	"io.containerd.snapshotter.v1.btrfs",
+	"io.containerd.snapshotter.v1.devmapper",
+	"io.containerd.snapshotter.v1.zfs",
+	"io.containerd.tracing.processor.v1.otlp",
+	"io.containerd.internal.v1.tracing",
+	"io.containerd.grpc.v1.cri",
```
Comment (sparr) [inline integration/config/etc/containerd/config.toml:11]: We currently successfully load the CRI plugin with a valid config. Is there any useful insight to share here before disabling it, even if tests are still passing?

Comment (Kern--) [reply integration/config/etc/containerd/config.toml:11]: From #377 
```
{"error":"cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config","level":"error","msg":"failed to load cni during init, please check CRI plugin status before setting up network for pods"
```

This is coming from the CRI plugin.

Comment (sparr) [reply integration/config/etc/containerd/config.toml:11]: Yes, but this says cni failed to load because there is no network config. cri is loading fine, I think? I guess we don't need it, since the tests pass, but disabling it isn't the same as disabling the ones that fail to load.

Comment (Kern--) [reply integration/config/etc/containerd/config.toml:11]: "cni plugin" here is not referring to a containerd plugin. CNI itself has a plugin system that allows you to write code that can set up arbitrary network configurations, you then string those plugins together via a network config. By default, the containerd CRI plugin assumes there will be a CNI network config of CNI plugins at `/etc/cni/net.d` and will try to load it. If it can't, CRI still starts up, but at this point it can't set up networking so it logs the error.

We could alternatively configure CRI to not look for that default CNI config (I think. It might override an empty config with the default that logs that message). Since we're not testing against kubernetes right now, I thought disabling the plugin would be easier than configuring it in a way that won't work if/when we do want to test against kubernetes.
