### PR TITLE
Fix flaky prefetcher unit tests

### LINKED ISSUE #24: Prefetch unit tests are flaky
**Describe the bug**
The prefetcher unit tests randomly fail with the error: `spans digest do not match`. 

**Steps To Reproduce**
- `cd` into `fs`

- Run the tests multiple times.

```
$ go clean -testcache && go test ./...

ok      github.com/awslabs/soci-snapshotter/fs    0.009s
?       github.com/awslabs/soci-snapshotter/fs/config    [no test files]
ok      github.com/awslabs/soci-snapshotter/fs/layer    8.559s
?       github.com/awslabs/soci-snapshotter/fs/metrics/common    [no test files]
?       github.com/awslabs/soci-snapshotter/fs/metrics/layer    [no test files]
ok      github.com/awslabs/soci-snapshotter/fs/reader    3.878s
ok      github.com/awslabs/soci-snapshotter/fs/remote    12.936s
?       github.com/awslabs/soci-snapshotter/fs/source    [no test files]
ok      github.com/awslabs/soci-snapshotter/fs/span-manager    0.629s

$ go clean -testcache && go test ./...
ok      github.com/awslabs/soci-snapshotter/fs    0.008s
?       github.com/awslabs/soci-snapshotter/fs/config    [no test files]
ok      github.com/awslabs/soci-snapshotter/fs/layer    8.671s
?       github.com/awslabs/soci-snapshotter/fs/metrics/common    [no test files]
?       github.com/awslabs/soci-snapshotter/fs/metrics/layer    [no test files]
ok      github.com/awslabs/soci-snapshotter/fs/reader    3.910s
ok      github.com/awslabs/soci-snapshotter/fs/remote    12.939s
?       github.com/awslabs/soci-snapshotter/fs/source    [no test files]
--- FAIL: TestStateTransition (0.00s)
    --- FAIL: TestStateTransition/max_span_-_prefetch (0.00s)
        span_manager_test.go:211: failed resolving the span for prefetch
    --- FAIL: TestStateTransition/max_span_-_on_demand_fetch (0.00s)
        span_manager_test.go:220: failed getting the span for on-demand fetch
FAIL
FAIL    github.com/awslabs/soci-snapshotter/fs/span-manager    0.631s
FAIL
```

**Expected behavior**
The prefetcher unit tests pass consistently. 

**Configuration (please complete the following information):**
 - OS: N/A
 - Snapshotter Version: Commit ID #714f1a971e6
 - Containerd Version: N/A

### PR DESCRIPTION
**Pull request by rdpsin**
*Issue #, if available:*
Fixes #24 

*Description of changes:*
- Fixed prefetcher unit tests failure. It was caused by garbage data during de-serialization of index data from binary blob.
- Updated `make check-dco` to start from commit c5989e95c. 

*Testing performed:*

Before:

```
$ for i in {0..100}; go clean -testcache; go test ./...; echo $?; done | grep 1 | wc -l
21
```

After:

```
$ for i in {0..100}; go clean -testcache; go test ./...; echo $?; done | grep 1 | wc -l
0
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: fs/span-manager/span_manager_test.go [hunk 1]
```diff
@@ -224,16 +224,16 @@ func TestStateTransition(t *testing.T) {
...
-					t.Fatalf("failed resolving the span for prefetch")
+					t.Fatalf("failed resolving the span for prefetch: %v", err)
 				}
 				state := s.state.Load().(spanState)
 				if state != fetched {
 					t.Fatalf("failed transitioning to Fetched state")
 				}
 			} else {
-				_, err := m.GetSpanContent(tc.spanID, 0, s.endUncompOffset, s.endUncompOffset-s.startUncompOffset)
+				_, err := m.GetSpanContent(tc.spanID, 0, s.endUncompOffset-s.startUncompOffset, s.endUncompOffset-s.startUncompOffset)
```
Comment (Kern--) [inline fs/span-manager/span_manager_test.go:234]: This seems weird given then signature:
```
GetSpanContent(spanID soci.SpanId, offsetStart, offsetEnd, size soci.FileSize)
```

I guess it doesn't matter since we're just checking for errors, not that the returned content is correct, but this should at least pass a sniff test.

Comment (rdpsin) [reply fs/span-manager/span_manager_test.go:234]: This is actually the correct implementation, if we want to fetch the whole span. The previous implementation would cause a panic due to a segfault.

Comment (Kern--) [reply fs/span-manager/span_manager_test.go:234]: Oh, I see. uncomp offset is relative to the full uncompressed buffer, but offsetStart/End in the definition is relative to the span, right?

Maybe creating a `span.Size()`  or `span.UncompressedSize()` function rather than having that logic all over would make it easier to read.

**Review by Kern-- — APPROVED** [review]

File: fs/span-manager/span_manager_test.go (hunk 1 above)
Comment (rdpsin) [reply fs/span-manager/span_manager_test.go:234]: Agreed.

**Review by vkuzniet — APPROVED** [review]
