### PR TITLE
Fix TestOverlayView in userns

### LINKED ISSUE #1573: [Bug] TestOverlayView  may fail with unexpected mount options
### Description

When running tests, it appears that the test `TestOverlayView` may result in the following error:

```
=== RUN   TestOverlayView
    snapshot_test.go:696: expected 1 mount option but got 2
--- FAIL: TestOverlayView (0.07s)
FAIL
```

### Steps to reproduce the bug

Unclear. It must be something specific to the test environment.

Please see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1103361 for the full conversation and context.

### Describe the results you expected

The test to pass

### Host information

1. OS:  Debian/trixie
2. Snapshotter Version:  0.4.1-4
3. Containerd Version: [1.7.24](https://packages.debian.org/source/testing/containerd)

### Any additional context or information about the bug

Applying the following patch:

```
-       if len(m.Options) != 1 {
-               t.Errorf("expected 1 mount option but got %d", len(m.Options))
-       }
+       if len(m.Options) != 1 {
+               t.Fatalf("expected 1 mount option but got %d: %+v", len(m.Options), m.Options)
+       }
```

shows this:

```
=== RUN   TestOverlayView
    snapshot_test.go:696: expected 1 mount option but got 2: [lowerdir=/tmp/TestOverlayView2389272231/001/snapshots/2/fs:/tmp/TestOverlayView2389272231/001/snapshots/1/fs userxattr]
```

I believe the first argument is expected, and the `userxattr` not?

### PR DESCRIPTION
**Pull request by Kern--**
**Issue #, if available:**
Fixes #1573

**Description of changes:**
TestOverlayView assumes that it is not run in a user namespace or that /tmp is a tmpfs. If it is run in a user namespace with a non-tmpfs /tmp, then the mount contains an additional `userxattr` mount option. This change checks if we expect that option and asserts on it as necessary.

**Testing performed:**
```
mkdir tmp
sudo mount --bind tmp /tmp
GO_TEST_FLAGS='-run TestOverlayView' unshare --user --map-current-user make test
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: snapshot/snapshot_test.go [hunk 1]
```diff
@@ -709,12 +710,20 @@ func TestOverlayView(t *testing.T) {
...
 	}
-	if len(m.Options) != 1 {
-		t.Errorf("expected 1 mount option but got %d", len(m.Options))
+	requiresUserXattrs, _ := overlayutils.NeedsUserXAttr("/tmp/view2")
+	expectedMountOptionsCount := 1
+	if requiresUserXattrs {
+		expectedMountOptionsCount = 2
+	}
+	if len(m.Options) != expectedMountOptionsCount {
+		t.Errorf("expected %d mount option(s) but got %d: %v", expectedMountOptionsCount, len(m.Options), m.Options)
```
Comment (austinvazquez) [inline snapshot/snapshot_test.go:719]: +1, thanks for adding the slice output as part of the assertion. :)
