### PR TITLE
Eagerly resolve local blobs

### LINKED ISSUE #931: [Bug] Layer not found error message
### Description

When attempting to run a container with a layer that does not contain a ztoc through the CRI API I receive an usual "not found" error message.

I will caveat this by saying the container still runs, but I’m unsure the repercussions of this message as it does not appear when running the same image through the containerd grpc api with nerdctl.

Error Message:

```
{
    "error": "cannot unpack the layer: cannot fetch layer: size of descriptor is 0; unable to resolve: unable to resolve ref (111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2): 111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2: not found",
    "key": "k8s.io/6/extract-389109763-ZI5T sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "warning",
    "msg": "failed to prepare snapshot; deferring to container runtime",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-09T21:07:03.452728891Z"
}
```

### Steps to reproduce the bug

The container image I have been using is a self built nginx container image, but the error message is not image dependent (as it appears on any non indexed image too, like the pause container image).

<details>
<summary>Self Built Container Image:</summary>

Dockerfile 

```
FROM public.ecr.aws/amazonlinux/amazonlinux:2

RUN amazon-linux-extras enable epel && \
    yum install -y epel-release && \
    yum install -y nginx

COPY index.html /usr/share/nginx/html/index.html

CMD ["nginx", "-g", "daemon off;"]
```

Index.html

```
<!DOCTYPE html>
<html>

<head>
    <title>Welcome to the SOCI Demo!</title>
    <style>
        html {
            color-scheme: light dark;
        }

        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
</head>

<body>
    <h1>Welcome to SOCI Demo!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
        working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
        <a href="http://nginx.org/">nginx.org</a>.<br />
        Commercial support is available at
        <a href="http://nginx.com/">nginx.com</a>.
    </p>

    <p><em>Thank you for using nginx.</em></p>
</body>

</html>
```

Container Image Manifest

`111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:1f6b58ad873037ea19d0b2e717cc1f60023963a7ea730a0686ec922545b47581`

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "digest": "sha256:9b3faf804fbe89052a4e489791e86d0e785827fd2a59e3690caaac488da848e3",
    "size": 1330
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:e6a2a106da1df9b5d4bfa74686415ac760f9d9999604e3784820d596e0983e27",
      "size": 62492148
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:0a0992534263fcf67d4b5ead3e49995e47e241995fec1051148292fe0ebd4c12",
      "size": 188770887
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
      "size": 629
    }
  ]
}
```

SOCI Index

`111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df`

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.amazon.soci.index.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/octet-stream",
      "digest": "sha256:04881d8ecc7c5d8cb0c01d391898caec9afe0d20da91a61e5c7ea8204455bf5b",
      "size": 3106904,
      "annotations": {
        "com.amazon.soci.image-layer-digest": "sha256:e6a2a106da1df9b5d4bfa74686415ac760f9d9999604e3784820d596e0983e27",
        "com.amazon.soci.image-layer-mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip"
      }
    },
    {
      "mediaType": "application/octet-stream",
      "digest": "sha256:e6f6ee873dfbe8a747c18ae134ffe61f40968ff22d74fa5959b2651da5e967e0",
      "size": 4365080,
      "annotations": {
        "com.amazon.soci.image-layer-digest": "sha256:0a0992534263fcf67d4b5ead3e49995e47e241995fec1051148292fe0ebd4c12",
        "com.amazon.soci.image-layer-mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip"
      }
    }
  ],
  "subject": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "digest": "sha256:1f6b58ad873037ea19d0b2e717cc1f60023963a7ea730a0686ec922545b47581",
    "size": 898
  },
  "annotations": {
    "com.amazon.soci.build-tool-identifier": "AWS SOCI CLI v0.1"
  }
}
```

</details>

My containerd config

```
version = 2

root = "/var/lib/containerd"
state = "/run/containerd"

[plugins]
  [proxy_plugins.soci]
    type = "snapshot"
    address = "/run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock"

  [plugins."io.containerd.grpc.v1.cri"]
    # Just pinning to a specific digest of registry.k8s.io/pause:3.9
    sandbox_image = "registry.k8s.io/pause@sha256:8d4106c88ec0bd28001e34c975d65175d994072d65341f62a8ab0754b0fafe10"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "soci"
      disable_snapshot_annotations = false
```

---

**Running with `nerdctl`**

```
$ nerdctl run --snapshotter soci --detach 111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest
111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest:                   resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:1f6b58ad873037ea19d0b2e717cc1f60023963a7ea730a0686ec922545b47581: done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:9b3faf804fbe89052a4e489791e86d0e785827fd2a59e3690caaac488da848e3:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 1.5 s                                                                    total:  2.2 Ki (1.4 KiB/s)                                       
27da62825f947a77eab611eab809fde130994896147c0cb57be7e8ce00261862

$ nerdctl ps
CONTAINER ID    IMAGE                                                             COMMAND                   CREATED          STATUS    PORTS    NAMES
27da62825f94    111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest    "nginx -g daemon off;"    4 minutes ago    Up                 nginx-demo-27da6
```

<details>
<summary>Snapshotter Logs showing 2 remote snapshots and 1 local snapshot</summary>

```
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "parent": "",
    "time": "2023-11-10T10:31:05.545927494Z"
}
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "index digest not provided, making a Referrers API call to fetch list of indices",
    "parent": "",
    "time": "2023-11-10T10:31:05.546017450Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "fetching SOCI artifacts using index descriptor",
    "parent": "",
    "time": "2023-11-10T10:31:05.669938145Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "level": "info",
    "msg": "fetching SOCI index from remote registry",
    "time": "2023-11-10T10:31:05.669982229Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:31:05.670029665Z"
}
{
    "digest": "sha256:e6f6ee873dfbe8a747c18ae134ffe61f40968ff22d74fa5959b2651da5e967e0",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:31:05.765965393Z"
}
{
    "digest": "sha256:04881d8ecc7c5d8cb0c01d391898caec9afe0d20da91a61e5c7ea8204455bf5b",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:31:05.765970817Z"
}
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "Received status code: 401 Unauthorized. Refreshing creds...",
    "parent": "",
    "src": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest/sha256:0a0992534263fcf67d4b5ead3e49995e47e241995fec1051148292fe0ebd4c12",
    "time": "2023-11-10T10:31:06.125028428Z"
}
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "Received status code: 401 Unauthorized. Refreshing creds...",
    "parent": "",
    "src": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest/sha256:e6a2a106da1df9b5d4bfa74686415ac760f9d9999604e3784820d596e0983e27",
    "time": "2023-11-10T10:31:06.125594058Z"
}
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "Verification forcefully skipped",
    "parent": "",
    "time": "2023-11-10T10:31:06.573774164Z"
}
{
    "key": "default/1/extract-541431167-69QF sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "msg": "remote snapshot successfully prepared.",
    "parent": "",
    "remote-snapshot-prepared": "true",
    "time": "2023-11-10T10:31:06.580144478Z"
}
{
    "key": "default/2/extract-584756795-z2cR sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/2/fs",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "time": "2023-11-10T10:31:06.588358222Z"
}
{
    "key": "default/2/extract-584756795-z2cR sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/2/fs",
    "msg": "Verification forcefully skipped",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "time": "2023-11-10T10:31:06.588504085Z"
}
{
    "key": "default/2/extract-584756795-z2cR sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "msg": "remote snapshot successfully prepared.",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "remote-snapshot-prepared": "true",
    "time": "2023-11-10T10:31:06.593693335Z"
}
{
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:31:06.601117922Z"
}
{
    "image": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest",
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "layerDigest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "msg": "skipping mounting layer as FUSE mount: no ztoc for layer",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:31:06.601209362Z"
}
{
    "error": "skipping mounting layer sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2 as FUSE mount: no ztoc for layer",
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "warning",
    "msg": "failed to prepare remote snapshot",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "remote-snapshot-prepared": "false",
    "time": "2023-11-10T10:31:06.601264202Z"
}
{
    "layerDigest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "level": "info",
    "msg": "preparing snapshot as local snapshot",
    "time": "2023-11-10T10:31:06.601427586Z"
}
{
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "preparing local filesystem at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:31:06.601458850Z"
}
{
    "digest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "fetching artifact from remote",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:31:06.601522128Z"
}
{
    "key": "default/3/extract-597895522-ZoZd sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "local snapshot successfully prepared",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:31:06.694161690Z"
}
```

</details>

---

**Running with `crictl`**

```
$ cat pod-config.json
{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "log_directory": "/tmp",
    "linux": {
    }
}

$ cat container-config.json
{
  "metadata": {
      "name": "nginxdemo"
  },
  "image":{
      "image": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest"
  },
  "log_path":"nginx.0.log",
  "linux": {
  }
}

$ TOKEN=$(aws ecr get-authorization-token --region eu-west-1 | jq -r '.authorizationData[0].authorizationToken' | base64 -d)

$ sudo crictl \
  --runtime-endpoint "unix:///var/run/containerd/containerd.sock" \
  --image-endpoint "unix:///var/run/containerd/containerd.sock" \
  run \
  --creds $TOKEN \
  container-config.json \
  pod-config.json

$ sudo crictl \
  --runtime-endpoint "unix:///var/run/containerd/containerd.sock" \
  pods
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT             RUNTIME
c674eb5332d7e       3 minutes ago       Ready               nginx-sandbox       default             1                   (default)

$ sudo crictl \
  --runtime-endpoint "unix:///var/run/containerd/containerd.sock" \
  ps
CONTAINER           IMAGE                                                            CREATED             STATE               NAME                ATTEMPT             POD ID              POD
a22995067ca0e       111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest   3 minutes ago       Running             nginxdemo           0                   c674eb5332d7e       unknown
```

<details>
<Summary>Snapshotter Logs for failed local snapshot for pause container</Summary>

```
{
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "parent": "",
    "time": "2023-11-10T10:58:22.915836434Z"
}
{
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "msg": "index digest not provided, making a Referrers API call to fetch list of indices",
    "parent": "",
    "time": "2023-11-10T10:58:22.915944996Z"
}
{
    "error": "unable to fetch SOCI artifacts: cannot fetch list of referrers: unable to fetch referrers: GET \"https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fconsole.cloud.google.com%2Fartifacts%2Ftags%2Fv2%2Feurope-west2%2Fk8s-artifacts-prod%2Fimages%252Fpause%252Freferrers%252Fsha256%2F8d4106c88ec0bd28001e34c975d65175d994072d65341f62a8ab0754b0fafe10\u0026followup=https%3A%2F%2Fconsole.cloud.google.com%2Fartifacts%2Ftags%2Fv2%2Feurope-west2%2Fk8s-artifacts-prod%2Fimages%252Fpause%252Freferrers%252Fsha256%2F8d4106c88ec0bd28001e34c975d65175d994072d65341f62a8ab0754b0fafe10\u0026ifkv=AVQVeyxNoNrCAv-K2lHSvMWhNk9GhWERQaP9ms_NJXF0_WgSmx93TAVDFvLrOZ3PCYh8O24wiu_K\u0026osid=1\u0026passive=1209600\u0026service=cloudconsole\u0026flowName=WebLiteSignIn\u0026flowEntry=ServiceLogin\u0026dsh=S755472317%3A1699613903093988\": failed to decode response: invalid character '\u003c' looking for beginning of value",
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "warning",
    "msg": "failed to prepare remote snapshot",
    "parent": "",
    "remote-snapshot-prepared": "false",
    "time": "2023-11-10T10:58:23.225310304Z"
}
{
    "layerDigest": "sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007",
    "level": "info",
    "msg": "preparing snapshot as local snapshot",
    "time": "2023-11-10T10:58:23.225370917Z"
}
{
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "info",
    "msg": "preparing local filesystem at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs",
    "parent": "",
    "time": "2023-11-10T10:58:23.225405422Z"
}
{
    "digest": "sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007",
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "info",
    "msg": "fetching artifact from remote",
    "parent": "",
    "time": "2023-11-10T10:58:23.225498491Z"
}
{
    "digest": "sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007",
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "warning",
    "msg": "size of descriptor is 0, trying to resolve it...",
    "parent": "",
    "time": "2023-11-10T10:58:23.225515000Z"
}
{
    "error": "cannot unpack the layer: cannot fetch layer: size of descriptor is 0; unable to resolve: unable to resolve ref (registry.k8s.io/pause@sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007): registry.k8s.io/pause@sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007: not found",
    "key": "k8s.io/1/extract-911068980-HwpE sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d",
    "level": "warning",
    "msg": "failed to prepare snapshot; deferring to container runtime",
    "parent": "",
    "time": "2023-11-10T10:58:23.347868140Z"
}
```

</details>

<details>
<Summary>Snapshotter Logs for Nginx Container. 2 Successful Remote Snapshots, 1 Failed local snapshot</Summary>

```
{
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "parent": "",
    "time": "2023-11-10T10:58:23.893369096Z"
}
{
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "msg": "index digest not provided, making a Referrers API call to fetch list of indices",
    "parent": "",
    "time": "2023-11-10T10:58:23.893446004Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "msg": "fetching SOCI artifacts using index descriptor",
    "parent": "",
    "time": "2023-11-10T10:58:24.098372503Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "level": "info",
    "msg": "fetching SOCI index from remote registry",
    "time": "2023-11-10T10:58:24.098413992Z"
}
{
    "digest": "sha256:90ae56adc78f9363b3b2397f87b9d5e971e004694120ccbc0b58cc8d4b5654df",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:58:24.098456319Z"
}
{
    "digest": "sha256:04881d8ecc7c5d8cb0c01d391898caec9afe0d20da91a61e5c7ea8204455bf5b",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:58:24.184183399Z"
}
{
    "digest": "sha256:e6f6ee873dfbe8a747c18ae134ffe61f40968ff22d74fa5959b2651da5e967e0",
    "level": "info",
    "msg": "fetching artifact from remote",
    "time": "2023-11-10T10:58:24.184210447Z"
}
{
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "msg": "Received status code: 401 Unauthorized. Refreshing creds...",
    "parent": "",
    "src": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest/sha256:e6a2a106da1df9b5d4bfa74686415ac760f9d9999604e3784820d596e0983e27",
    "time": "2023-11-10T10:58:24.493977616Z"
}
{
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs",
    "msg": "Verification forcefully skipped",
    "parent": "",
    "time": "2023-11-10T10:58:24.894619999Z"
}
{
    "key": "k8s.io/4/extract-889519745-F-vT sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "level": "info",
    "msg": "remote snapshot successfully prepared.",
    "parent": "",
    "remote-snapshot-prepared": "true",
    "time": "2023-11-10T10:58:24.900188272Z"
}
{
    "key": "k8s.io/5/extract-921454245-nQMe sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/4/fs",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "time": "2023-11-10T10:58:24.924948947Z"
}
{
    "key": "k8s.io/5/extract-921454245-nQMe sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/4/fs",
    "msg": "Received status code: 401 Unauthorized. Refreshing creds...",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "src": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest/sha256:0a0992534263fcf67d4b5ead3e49995e47e241995fec1051148292fe0ebd4c12",
    "time": "2023-11-10T10:58:24.932276438Z"
}
{
    "key": "k8s.io/5/extract-921454245-nQMe sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/4/fs",
    "msg": "Verification forcefully skipped",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "time": "2023-11-10T10:58:25.315583990Z"
}
{
    "key": "k8s.io/5/extract-921454245-nQMe sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "level": "info",
    "msg": "remote snapshot successfully prepared.",
    "parent": "sha256:5456d740f71ce2e23882740d2d87a61ad270a5ba2679dede61fd8541e4277d29",
    "remote-snapshot-prepared": "true",
    "time": "2023-11-10T10:58:25.322447547Z"
}
{
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.330450563Z"
}
{
    "image": "111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo:latest",
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "layerDigest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "level": "info",
    "mountpoint": "/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs",
    "msg": "skipping mounting layer as FUSE mount: no ztoc for layer",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.330536859Z"
}
{
    "error": "skipping mounting layer sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2 as FUSE mount: no ztoc for layer",
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "warning",
    "msg": "failed to prepare remote snapshot",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "remote-snapshot-prepared": "false",
    "time": "2023-11-10T10:58:25.330584665Z"
}
{
    "layerDigest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "level": "info",
    "msg": "preparing snapshot as local snapshot",
    "time": "2023-11-10T10:58:25.330688150Z"
}
{
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "preparing local filesystem at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.330714499Z"
}
{
    "digest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "info",
    "msg": "fetching artifact from remote",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.330773723Z"
}
{
    "digest": "sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2",
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "warning",
    "msg": "size of descriptor is 0, trying to resolve it...",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.330787676Z"
}
{
    "error": "cannot unpack the layer: cannot fetch layer: size of descriptor is 0; unable to resolve: unable to resolve ref (111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2): 111222333444.dkr.ecr.eu-west-1.amazonaws.com/nginx-demo@sha256:4dbc43c9a102fbf8cfc991788f21b809b9aa10d365bf4aaf9d1ef22ffb0e8db2: not found",
    "key": "k8s.io/6/extract-327009088-xpeP sha256:5fcd89177512660e58f6bd7596bd41b0a0ac94912b14bc13b11ebee594ce79ef",
    "level": "warning",
    "msg": "failed to prepare snapshot; deferring to container runtime",
    "parent": "sha256:7743d89969b2f11448ff9c3c7d0b67768bf706d37581e804f3cc4b44be22687e",
    "time": "2023-11-10T10:58:25.387041197Z"
}
```

</details>

### Describe the results you expected

I was expecting the SOCI snapshotter to create a local snapshot.

### Host information

```
$ uname -a
Linux ip-172-31-19-9.eu-west-1.compute.internal 5.10.198-187.748.amzn2.x86_64 #1 SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

$ sudo ctr --version
ctr github.com/containerd/containerd 1.6.19

$ sudo nerdctl --version
nerdctl version 1.7.0

$ sudo soci --version
soci version v0.4.0 894c8ece8a2177928343899b1f897d2164c98254

$ sudo crictl --version
crictl version v1.28.0
```

### Any additional context or information about the bug

_No response_

### PR DESCRIPTION
**Pull request by sondavidb**
**Issue #, if available:**
Fixes #931

**Description of changes:**
For local snapshots, we previously encountered a bug where the size of a layer was resported as zero in its descriptor. This caused the Fetch function to attempt to resolve it as a manifest, which would then cause the local snapshot to defer to container runtime, causing containerd to fetch all remaining layers ahead of time. This change resolves the local blob earlier to populate the size field, avoiding this issue.

**Testing performed:**
Followed steps in #931 and ensured local snapshots were successfully prepared.

After setting up containerd/crictl configs I ran the following script:

```
# Empty content store beforehand

TOKEN=$(aws ecr get-authorization-token --region us-west-2 | jq -r '.authorizationData[0].authorizationToken' | base64 -d)
sudo crictl \
  --runtime-endpoint "unix:///var/run/containerd/containerd.sock" \
  --image-endpoint "unix:///var/run/containerd/containerd.sock" \
  run \
  --creds $TOKEN \
  container-config.json \
  pod-config.json
```

<details>
  <summary>Output</summary>

``` json
{"level":"info","msg":"starting soci-snapshotter-grpc","revision":"5217c3718d46a675fb964ff06c2399540b03794e","time":"2024-01-09T21:56:31.727674500Z","version":"5217c37"}
{"emitMetricPeriod":10000000000,"fetchPeriod":500000000,"level":"info","maxQueueSize":100,"msg":"constructing background fetcher","silencePeriod":30000000000,"time":"2024-01-09T21:56:31.763298289Z"}
{"address":"/run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock","level":"info","msg":"soci-snapshotter-grpc successfully started","time":"2024-01-09T21:56:31.767434398Z"}
{"key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs","parent":"","time":"2024-01-09T21:56:32.550227833Z"}
{"key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs","msg":"index digest not provided, making a Referrers API call to fetch list of indices","parent":"","time":"2024-01-09T21:56:32.550317570Z"}
{"error":"unable to fetch SOCI artifacts: cannot fetch list of referrers: unable to fetch referrers: GET \"https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fconsole.cloud.google.com%2Fartifacts%2Ftags%2Fv2%2Fus-west1%2Fk8s-artifacts-prod%2Fimages%252Fpause%252Freferrers%252Fsha256%2F8d4106c88ec0bd28001e34c975d65175d994072d65341f62a8ab0754b0fafe10\u0026followup=https%3A%2F%2Fconsole.cloud.google.com%2Fartifacts%2Ftags%2Fv2%2Fus-west1%2Fk8s-artifacts-prod%2Fimages%252Fpause%252Freferrers%252Fsha256%2F8d4106c88ec0bd28001e34c975d65175d994072d65341f62a8ab0754b0fafe10\u0026ifkv=ASKXGp2557sFr8K0acu6KQXE9y8yxDkTNaD4RnM82YUOVq6iCWSnQMBGS4ZPj_NXyXuExnKCWQ10Sw\u0026osid=1\u0026passive=1209600\u0026service=cloudconsole\u0026flowName=WebLiteSignIn\u0026flowEntry=ServiceLogin\u0026dsh=S111108%3A1704837392875678\": failed to decode response: invalid character '\u003c' looking for beginning of value","key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"warning","msg":"failed to prepare remote snapshot","parent":"","remote-snapshot-prepared":"false","time":"2024-01-09T21:56:33.057822171Z"}
{"layerDigest":"sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007","level":"info","msg":"preparing snapshot as local snapshot","time":"2024-01-09T21:56:33.057880065Z"}
{"key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"info","msg":"preparing local filesystem at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/1/fs","parent":"","time":"2024-01-09T21:56:33.057905931Z"}
{"digest":"sha256:61fec91190a0bab34406027bbec43d562218df6e80d22d4735029756f23c7007","key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"info","msg":"fetching artifact from remote","parent":"","time":"2024-01-09T21:56:33.115622050Z"}
{"key":"k8s.io/1/extract-544072554-KtoC sha256:e3e5579ddd43c08e4b5c74dc12941a4ef656fab070b1087a1fd5a8a836b71e7d","level":"info","msg":"local snapshot successfully prepared","parent":"","time":"2024-01-09T21:56:33.170098068Z"}
{"key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs","parent":"","time":"2024-01-09T21:56:33.637428598Z"}
{"key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs","msg":"index digest not provided, making a Referrers API call to fetch list of indices","parent":"","time":"2024-01-09T21:56:33.637517943Z"}
{"key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs","msg":"Received status code: 401 Unauthorized. Authorizing...","parent":"","time":"2024-01-09T21:56:33.655293258Z"}
{"digest":"sha256:bed193e8a077047e03e0775f8827fca3d9bd5c555e429b95c797ed2ffbb87fbf","key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs","msg":"fetching SOCI artifacts using index descriptor","parent":"","time":"2024-01-09T21:56:33.785765708Z"}
{"digest":"sha256:bed193e8a077047e03e0775f8827fca3d9bd5c555e429b95c797ed2ffbb87fbf","level":"info","msg":"fetching SOCI index from remote registry","time":"2024-01-09T21:56:33.785797153Z"}
{"digest":"sha256:bed193e8a077047e03e0775f8827fca3d9bd5c555e429b95c797ed2ffbb87fbf","level":"info","msg":"fetching artifact from remote","time":"2024-01-09T21:56:33.785832098Z"}
{"digest":"sha256:5f931294fa10c999223fb7c19ff241ecb3cdfcb0b61d9289da8d7562d51c7778","level":"info","msg":"fetching artifact from remote","time":"2024-01-09T21:56:33.870896973Z"}
{"digest":"sha256:3baf6beca7e66fd9f202a0e80d22a446927f7f3b8e0bab208758c4ca1258aee9","level":"info","msg":"fetching artifact from remote","time":"2024-01-09T21:56:33.870904590Z"}
{"key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/3/fs","msg":"Verification forcefully skipped","parent":"","time":"2024-01-09T21:56:34.495312457Z"}
{"key":"k8s.io/3/extract-634603292-LAsg sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","level":"info","msg":"remote snapshot successfully prepared.","parent":"","remote-snapshot-prepared":"true","time":"2024-01-09T21:56:34.499215012Z"}
{"key":"k8s.io/4/extract-504004840-sQgj sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/4/fs","parent":"sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","time":"2024-01-09T21:56:34.507123341Z"}
{"key":"k8s.io/4/extract-504004840-sQgj sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/4/fs","msg":"Verification forcefully skipped","parent":"sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","time":"2024-01-09T21:56:34.787930976Z"}
{"key":"k8s.io/4/extract-504004840-sQgj sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","level":"info","msg":"remote snapshot successfully prepared.","parent":"sha256:8075d045345a93dbac9815a69cdee7f0d10ba82e83f364c794683b31f3a82c86","remote-snapshot-prepared":"true","time":"2024-01-09T21:56:34.792532731Z"}
{"key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","level":"info","msg":"preparing filesystem mount at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","time":"2024-01-09T21:56:34.799303025Z"}
{"image":"425784566319.dkr.ecr.us-west-2.amazonaws.com/testing:nginx-demo","key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","layerDigest":"sha256:e95787efecdd4b6afe3e32d9d6ddb1ad8605754b4c73c1a4637135c63c684247","level":"info","mountpoint":"/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs","msg":"skipping mounting layer as FUSE mount: no ztoc for layer","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","time":"2024-01-09T21:56:34.799375369Z"}
{"error":"skipping mounting layer sha256:e95787efecdd4b6afe3e32d9d6ddb1ad8605754b4c73c1a4637135c63c684247 as FUSE mount: no ztoc for layer","key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","level":"warning","msg":"failed to prepare remote snapshot","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","remote-snapshot-prepared":"false","time":"2024-01-09T21:56:34.799414383Z"}
{"layerDigest":"sha256:e95787efecdd4b6afe3e32d9d6ddb1ad8605754b4c73c1a4637135c63c684247","level":"info","msg":"preparing snapshot as local snapshot","time":"2024-01-09T21:56:34.799481264Z"}
{"key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","level":"info","msg":"preparing local filesystem at mountpoint=/var/lib/soci-snapshotter-grpc/snapshotter/snapshots/5/fs","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","time":"2024-01-09T21:56:34.799499214Z"}
{"digest":"sha256:e95787efecdd4b6afe3e32d9d6ddb1ad8605754b4c73c1a4637135c63c684247","key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","level":"info","msg":"fetching artifact from remote","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","time":"2024-01-09T21:56:34.848547041Z"}
{"key":"k8s.io/5/extract-795965430-Z2XQ sha256:ed65b89030c460f72fc00e77fbd1a49514d7db99128cd3f8dd692bad4cd65eaa","level":"info","msg":"local snapshot successfully prepared","parent":"sha256:fb0172ff7e95acb9f733f1974fde617f9f4194d6ba3e4f9486791fe35553e1b8","time":"2024-01-09T21:56:34.922153837Z"}
```
</details>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: fs/fs.go [hunk 1]
```diff
@@ -346,6 +346,19 @@ func (fs *filesystem) MountLocal(ctx context.Context, mountpoint string, labels
 	}
 	unpacker := NewLayerUnpacker(fetcher, archive)
 	desc := s.Target
+
+	// If no descriptor size is given, resolve the layer
+	// to populate it
+	if desc.Size == 0 {
+		// In remoteStore.Reference, Registry and Target will always be correct.
+		// However, we need to update Reference to point to the correct digest
+		remoteStore.Reference.Reference = s.Target.Digest.String()
```
Comment (Kern--) [inline fs/fs.go:355]: nit: Since we're giving the remote store to the `ArtifactFetcher`, I think we should avoid modifying the internal reference. It probably doesn't matter much in practice, but I think it's easier to reason about if the remote repository always contains an image ref rather than a random blob ref.


The `Reference` field isn't a pointer, so we can just add:
```
blobRef := remoteStore.Reference
blobRef.Reference = s.Target.Digest.String()
```

File: fs/fs.go [hunk 2]
```diff
@@ -346,6 +346,19 @@ func (fs *filesystem) MountLocal(ctx context.Context, mountpoint string, labels
...
+		desc, err = remoteStore.Blobs().Resolve(ctx, remoteStore.Reference.String())
+		if err != nil {
+			return fmt.Errorf("cannot resolve local blobs %s: %w", remoteStore.Reference.String(), err)
```
Comment (Kern--) [inline fs/fs.go:358]: nit: I'm not sure this message is clear without knowing the implementation details. What about:
```
"cannot resolve size of layer %s: %w"
```

Comment (turan18) [reply fs/fs.go:358]: Agreed. What ever it is, I think we should keep the error format consistent with https://github.com/awslabs/soci-snapshotter/blob/95c139e65a4bdfca058cec324403afad0f8fcd58/fs/artifact_fetcher.go#L121.

File: fs/fs.go (hunk 1 above)
Comment (sondavidb) [reply fs/fs.go:355]: I was thinking about this too, but since this is done per layer, I thought it would make it more accurate to show exactly which blob is being resolved. Though, thinking about it again, it would also take away the version tag, which as you mentioned would then make it more difficult to find out exactly which image is being changed. So, you're probably right. I'll make that change.

**Comment by turan18** [comment]
LGTM, pending nits.

**Review by Kern-- — APPROVED** [review]
