### PR TITLE
Fail integration tests immediately on fatal soci error

### LINKED ISSUE #371: [BUG] invalid config.toml leads to integration test being re-run 100 times
**Describe the bug**
When an integration test creates an environment with an invalid config.toml file, specifically with a string where an int is expected but possibly other cases as well, this results in the test being re-run 100 times instead of completely failing. Each attempt fails to connect to soci-snapshotter-grpc.

**Steps To Reproduce**
Replace the snapshotter config line (containing `getSnapshotterConfigYaml`) in an existing test with the following:

`testutil.WriteFileContents(sh, defaultSnapshotterConfigPath, getSnapshotterConfigYaml(t, false, "\nresolve_result_entry=\"123\"\n"), 0600); err != nil {`

then run that test with `GO_TEST_FLAGS="-run NAMEOFTHETEST -count=1" make integration`
	
**Expected behavior**
Test completely fails when soci-snapshotter-grpc fails to start, rather than continuing then trying to connect to it repeatedly.

**Configuration (please complete the following information):**
 - OS: Amazon Linux
 - Snapshotter Version: recent master
 - Containerd Version: 1.6.13

**Additional context**
This behavior is caused by https://github.com/awslabs/soci-snapshotter/blob/b3a62fe0e8985cfc152bf867c8e287969b34a2e3/integration/testutil.go#L566-L574 which uses a `sh.Retry(100` to detect when soci-snapshotter-grpc has finished launching. The `sh.R` that launches soci-snapshotter-grpc unfortunately doesn't directly surface the exit status/code from the process, but there may be some other way to more immediately detect the failure, such as errors in the log output, or the process ending before the log shows a successful launch. #376 has some overlap with this behavior.

Partial output from original effort that led to discovering this:

    {"level":"info","msg":"containerd successfully booted in 0.036189s","time":"2023-01-30T20:57:01.794579257Z"}
    {"error":"(5, 1): Can't convert 123(string) to int","level":"fatal","msg":"failed to unmarshal config file \"/etc/soci-snapshotter-grpc/config.toml\"","time":"2023-01-30T20:57:01.802858531Z"}
    {"key":"connectiontest-dummy-cfc2u7aufki8c8kjhmag","level":"debug","msg":"prepare snapshot","parent":"","time":"2023-01-30T20:57:01.805276574Z"}
    {"d":120608,"level":"debug","msg":"garbage collected","time":"2023-01-30T20:57:01.889485943Z"}
    ctr: connection error: desc = "transport: Error while dialing dial unix:///run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock: timeout": unavailable
    testing: 2023/01/30 20:57:02 failed to run (0/100) [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]: exit status 1
        shell.go:76: failed to run (0/100) [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]: exit status 1
    testing: 2023/01/30 20:57:03 >>> Running(1/100): [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]
        shell.go:76: >>> Running(1/100): [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]
    {"key":"connectiontest-dummy-cfc2u7aufki8c8kjhmag","level":"debug","msg":"prepare snapshot","parent":"","time":"2023-01-30T20:57:03.878457766Z"}
    ctr: connection error: desc = "transport: Error while dialing dial unix:///run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock: timeout": unavailable
    testing: 2023/01/30 20:57:05 failed to run (1/100) [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]: exit status 1
        shell.go:76: failed to run (1/100) [ctr snapshots --snapshotter soci prepare connectiontest-dummy-cfc2u7aufki8c8kjhmag ]: exit status 1
    testing: 2023/01/30 20:57:06 >>> Running(2/100):

### PR DESCRIPTION
**Pull request by sparr**
**Issue #, if available:**
Fixes #371 

**Description of changes:**
This PR adds a second io.Reader scanner to the soci output logs during integration tests, focused on spotting fatal errors. When a fatal error is found, the test is aborted immediately instead of allowing further downstream retries to continue.

**Testing performed:**
Ran a modified integration test to produce an invalid config.toml, confirmed test bails as soon as soci-snapshotter-grpc logs the config invalidity as a fatal error. Previous behavior (100 retries to make connection from ctr to running soci-snapshotter-grpc) is gone.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sparr** [comment]
Should we be writing tests for the test infrastructure? That would be a new step for the project, but here it might be useful to test that this bails out and doesn't in the appropriate scenarios.

File: util/testutil/shell.go [hunk 1]
```diff
@@ -141,6 +142,42 @@ func (m *RemoteSnapshotMonitor) CheckAllRemoteSnapshots(t *testing.T) {
...
+	}
+}
+
+type LevelLogLine struct {
+	Level string `json:"level"`
+	Msg   string `json:"msg"`
+}
+
+// ScanFatalLog scans the log streamed from the specified io.Reader for fatal errors during startup
+func ScanFatalLog(inputR io.Reader, errs chan error) {
```
Comment (djdongjin) [inline util/testutil/shell.go:162]: If it's only used by `FatalMonitor`, `ScanFatalLog` can be un-exported.

File: util/testutil/shell.go [hunk 2]
```diff
@@ -141,6 +142,42 @@ func (m *RemoteSnapshotMonitor) CheckAllRemoteSnapshots(t *testing.T) {
...
+	scanner := bufio.NewScanner(inputR)
+	var logline LevelLogLine
+	for scanner.Scan() {
+		rawL := scanner.Text()
+		if i := strings.Index(rawL, "{"); i > 0 {
+			rawL = rawL[i:] // trim garbage chars; expects "{...}"-styled JSON log
+		}
+		if err := json.Unmarshal([]byte(rawL), &logline); err == nil {
```
Comment (turan18) [inline util/testutil/shell.go:170]: We could make `LevelLogLine` an anonymous struct if we presume it will only be used here

File: util/testutil/shell.go [hunk 3]
```diff
@@ -141,6 +142,42 @@ func (m *RemoteSnapshotMonitor) CheckAllRemoteSnapshots(t *testing.T) {
...
+	errs := make(chan error, 1)
+	go ScanFatalLog(io.TeeReader(stdout, r.Stdout()), errs)
+	go ScanFatalLog(io.TeeReader(stderr, r.Stderr()), errs)
+	err := <-errs
+	if err != nil {
+		r.Errorf(err.Error())
+	}
+}
+
+type LevelLogLine struct {
```
Comment (djdongjin) [inline util/testutil/shell.go:156]: same for the struct.

File: util/testutil/shell.go [hunk 4]
```diff
@@ -141,6 +142,42 @@ func (m *RemoteSnapshotMonitor) CheckAllRemoteSnapshots(t *testing.T) {
...
+	scanner := bufio.NewScanner(inputR)
+	var logline LevelLogLine
+	for scanner.Scan() {
+		rawL := scanner.Text()
+		if i := strings.Index(rawL, "{"); i > 0 {
+			rawL = rawL[i:] // trim garbage chars; expects "{...}"-styled JSON log
+		}
+		if err := json.Unmarshal([]byte(rawL), &logline); err == nil {
+			if logline.Level == "fatal" {
+				errs <- errors.New("fatal snapshotter log entry encountered")
```
Comment (Kern--) [inline util/testutil/shell.go:172]:
```suggestion
				errs <- errors.New("aborting test: fatal snapshotter log entry encountered")
```

Comment (Kern--) [reply util/testutil/shell.go:172]: Or maybe this should stay as it is and `FatalMonitor` should wrap the error with "aborting test" before sending the error to the reporter?

**Comment by djdongjin** [comment]
The CI looks like dead-locked (has run for 5 hours). We probably should add a timeout either on `go test` or on github action.

File: util/testutil/shell.go (hunk 2 above)
Comment (sparr) [reply util/testutil/shell.go:170]: I expect it will be used by #520 and other log monitors that are created in the near future.

File: util/testutil/shell.go (hunk 3 above)
Comment (sparr) [reply util/testutil/shell.go:156]: This one is exported intentionally, in expectation of #520 and later new monitors using it.

**Review by Kern-- — DISMISSED** [review]

**Review by turan18 — APPROVED** [review]

File: util/testutil/shell.go [hunk 5]
```diff
@@ -141,6 +143,46 @@ func (m *RemoteSnapshotMonitor) CheckAllRemoteSnapshots(t *testing.T) {
...
+	for scanner.Scan() {
+		rawL := scanner.Text()
+		if i := strings.Index(rawL, "{"); i > 0 {
+			rawL = rawL[i:] // trim garbage chars; expects "{...}"-styled JSON log
+		}
+		if err := json.Unmarshal([]byte(rawL), &logline); err == nil {
+			if logline.Level == "fatal" {
+				errs <- errors.New("aborting test: fatal snapshotter log entry encountered")
+			}
+			if strings.Contains(logline.Msg, "background") {
```
Comment (Kern--) [inline util/testutil/shell.go:179]: Noting that we already have an issue to make this more robust: https://github.com/awslabs/soci-snapshotter/issues/515#issuecomment-1479956859

**Review by Kern-- — APPROVED** [review]

**Review by djdongjin — APPROVED** [review]
