### PR TITLE
Fix integrations tests with cgroupv2

### LINKED ISSUE #735: [Bug] Integration tests don't work with cgroupv2
### Description

When running the integration tests on a host machine that uses cgroupsv2, the tests fail with errors about cgroupv2 being in an invalid state.

It looks like Docker had this same problem and has a script to initialize cgroupv2 for nesting properly: https://github.com/moby/moby/pull/41065

### Steps to reproduce the bug

Run any test that tries to run a container on a host that's configured for cgroupsv2. Observe container failures due to cgroups being in an invalid state;

```
$ STATIC=1 GO_TEST_FLAGS='-run TestLazyPull' make integration
...
ctr: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: cannot enter cgroupv2 "/sys/fs/cgroup/default" with domain controllers -- it is in an invalid state: unknown
```

### Describe the results you expected

The tests should pass when the host is configured for cgroupv2.

### Host information

1. OS: AL2023
2. Snapshotter Version: soci-snapshotter-grpc version 08dcb20 08dcb2097d0389019ffa2531b784f3910cd7451a
3. Containerd Version: 1.6.19

### Any additional context or information about the bug

_No response_

### PR DESCRIPTION
**Pull request by Kern--**
**Issue #, if available:**
closes #735 

**Description of changes:**
With cgroupv2, dind doesn't work out of the box because the inner docker process is in the (containerized) root cgroup so it can't create the inner container's cgroups because doing so would make the inner docker a process on an interior cgroup node. cgroupv2 only allows processes on the leaf nodes.

The solution is to move docker to a child cgroup (called init) so that the container can exist as a sibling.

**Testing performed:**
`make check && make integration` on an al2023 instance which uses cgroupv2. 

Before this change the tests failed with:
```
ctr: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: cannot enter cgroupv2 "/sys/fs/cgroup/default" with domain controllers -- it is in an invalid state: unknown
```

after this change, the tests pass

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by sondavidb — APPROVED** [review]

File: integ_entrypoint.sh [hunk 1]
```diff
@@ -0,0 +1,34 @@
+#!/bin/bash
```
Comment (turan18) [inline integ_entrypoint.sh:1]: nit: Should this be under `.scripts/`?

**Review by turan18 — APPROVED** [review]

File: integ_entrypoint.sh (hunk 1 above)
Comment (Kern--) [reply integ_entrypoint.sh:1]: I didn't put it under `scripts` because those are generally project level scripts and this is really integration test code. I put it in the root to live next to the Dockerfile.

Personally, I think we should move both the Dockerfile and setup script into `integration` somewhere.
